apiVersion: v1
kind: Pod
metadata:
  name: volume-with-secrets
spec: 
  containers:
    - name: app
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: secret-volume
          mountPath: /secret
          readOnly: true

  volumes:
    - name: secret-volume
      secret:
        secretName: secret-2

