services:

  backend:
    build : ./backend
    depends_on: 
      redis:
        condition: service_healthy 
    env_file:
      - ./backend/.env
    networks:
      - dp_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M



  redis:
    image: redis:alpine
    volumes:
      - dp_data:/data
    networks:
      - dp_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
    restart: always


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dp_network
    ports:
      - "80:80"
    depends_on:
      - frontend
    restart: always

  
  frontend:
    build:  ./frontend
    depends_on:
      - backend
    networks:
      - dp_network
    restart: always


volumes:
  dp_data:

networks:
  dp_network: