services:
  backend:
    build: ./backend
    depends_on:
      - redis
    environment:
      - Redis_Host=redis
      - Redis_Port=6379
    networks:
      - dp_network

  redis:
    image: redis:alpine
    volumes:
      - dstar:/data
    networks:
      - dp_network

  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dp_network


volumes:
  dstar:
  
networks:
  dp_network: