apiVersion: v1
kind: Pod
metadata:
  name: pod-for-secret
spec: 
  containers:
    - name: app
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      envFrom:
        - secretRef:
            name: secret-1

