services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - Redis_Host=redis
      - Redis_Port=6379
    networks:
      - dp_network

  redis:
    image: redis:alpine
    volumes:
      -  dp_data:/data
    ports:
      -  "6379:6379"
    networks:
      - dp_network

volumes:
  dp_data:

networks:
  dp_network:
