apiVersion: v1
kind: Pod
metadata:
  name: sc-pod
spec:
  containers: 
    - name: app
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: data
          mountPath: /app 

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: sc-pvc

