apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: vivek
subjects:
- kind: ServiceAccount
  name: readonly-user
  namespace: vivek
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io