apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume
spec:
  containers:
    - name: app
      image: busybox
      command: ['sh', '-c', 'sleep 3300']
      volumeMounts:
        - name: emptydir-vol
          mountPath: /data
  
  volumes:
    - name: emptydir-vol
      emptyDir: {}

