apiVersion: apps/v1
kind: Deployment
metadata: 
  name: diwakar-deployment
  namespace: vivek
  annotations:
    owner: diwakar
    networth: "108 billion dollars"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: r-news
      env: welcome
  template:
    metadata:
      labels:
        app: r-news
        env: welcome
    spec:
      containers:
        - name: diwakar-deployment-container
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"


