apiVersion: v1
kind: Pod
metadata: 
  name: configmap-in-files
spec:
  containers:
    - name: dp-container-2
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config      

  volumes:
    - name: config-volume
      configMap:
        name: pehla-config


