apiVersion: v1
kind: ResourceQuota
metadata:
  name: task-dev-quota
  namespace: task
spec:
  hard:
    pods: 5
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"

