apiVersion: v1
kind: Pod
metadata:
  name: third-pod-for-limitrange
  namespace: dev
  annotations:
    owner: diwakar
    networth: 300-billion-dollars
spec:
  containers:
    - name: app
      image: busybox
      command: ['sh', '-c', 'sleep 7200']

