apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resourcequota
  namespace: dev
spec:
  hard:
    pods: "5"
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1000m"
    limits.memory: "1024Mi"


