apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: dev
spec:
  limits:
    - type: Container
      default:
        cpu: '150m'
        memory: '150Mi'
      defaultRequest:
        cpu: '50m'
        memory: '50Mi'
